<?php

namespace AppBundle\Repository;

use AppBundle\Entity\TableHolidaysForEmployee;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * TableHolidaysForEmployeeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TableHolidaysForEmployeeRepository extends ServiceEntityRepository
{
    public function findHolidaysWhereUserId($userId)
    {
        return $this->getEntityManager()
                    ->createQueryBuilder()
                    ->select('h')
                    ->from('AppBundle:TableHolidaysForEmployee', 'h')
                    ->where("h.userId=:userId")
                    ->setParameter('userId', $userId)
                    ->getQuery()
                    ->getResult();
    }

    public function getAllHolidays()
    {
        return $this->getEntityManager()
                    ->createQueryBuilder()
                    ->select('h')
                    ->from('AppBundle:TableHolidaysForEmployee', 'h')
                    ->getQuery()
                    ->getResult();
    }

    public function save($numberOfDaysOff)
    {
        $tableHolidaysForEmployee = new TableHolidaysForEmployee();
        $tableHolidaysForEmployee->setNumberOfDaysOff($numberOfDaysOff);
        $this->getEntityManager()->persist($tableHolidaysForEmployee);
        $this->getEntityManager()->flush();
    }
}
