<?php

namespace AppBundle\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends ServiceEntityRepository
{
    public function getAll()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('t')
            ->from('AppBundle:Team', 't')
            ->getQuery()
            ->getResult();
    }
}
